name: run-github-workflows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  solve-environments-and-upload-artifacts:
    name: solve .yml file with micromamba
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: check what's inside the miniconda installation
      run: |
        cd /c/Miniconda/etc/profile.d
        ls -la
        cat conda.sh
    - name: initialize conda for Git Bash
      run: |
        echo ". /c/Miniconda/etc/profile.d/conda.sh" >> ~/.bashrc
    - name: test conda
      run: |
        conda env list
        conda env export -n base > ./base.yml
        ls -la
