name: run-github-workflows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-yml-file:
    name: test-yml-file
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        channel-priority: strict
        environment-file: test_input.yml
    - name: print conda info
      run: |
        conda info
        conda list
    - name: export conda environment
      run: |
        echo "$PWD"
        conda env export --name test > test_output.yml
        ls -la
