name: run-github-workflows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  solve-environments-and-upload-artifacts:
    name: solve .yml file with micromamba
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: initialize conda for Git Bash
      run: |
        echo ". /c/Miniconda/etc/profile.d/conda.sh" >> ~/.bashrc
    - name: setup micromamba and solve environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ./environments/environment.yml
        environment-name: test
    - name: export pip-packages
      run: |
        pip freeze > requirements.txt
        cat requirements.txt
