name: run-github-workflows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  solve-ymls:
    name: solve .yml file with micromamba
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: run tcy to create .yml file
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          touch ${{ matrix.os }}.txt && echo ${{ matrix.os }} >> ${{ matrix.os }}.txt
          ls -la
        elif [ "$RUNNER_OS" == "Windows" ]; then
          touch ${{ matrix.os }}.txt && echo ${{ matrix.os }} >> ${{ matrix.os }}.txt
          ls -la
        fi
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: ${{ matrix.os }}.txt
  download-artifacts-and-push:
    name: download artifacts and push to repo
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: download multiple artifacts
      uses: marcofaggian/action-download-multiple-artifacts@v1
      with:
        names: ubuntu-latest windows-latest
        paths: ./environments/ubuntu-latest.txt ./environments/windows-latest.txt
    - name: Print the final result
      shell: bash
      run: |
        cd environments
        ls -la
