name: run-github-workflows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-yml-file:
    name: test-yml-file
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        channel-priority: strict
        environment-file: environment.yml
    - name: print conda info
      shell: bash -el {0}
      run: |
        conda info
        conda list
