name: run-github-workflows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-yml-micromamba:
    needs: check-tsv-file
    name: solve .yml file with micromamba
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: setup micromamba and solve environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        environment-name: ${{ runner.os }}
    - name: export conda environment created using micromamba
      run: |
        micromamba env export --name csp_surname_name | grep -v "^prefix: " > ./environments/environment_solved_${{ runner.os }}.yml
    - name: add and commit exported conda environment
      uses: stefanzweifel/git-auto-commit-action@v4


