name: run-github-workflows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  solve-environments-and-upload-artifacts:
    name: solve .yml file with micromamba
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: check what's inside miniconda
      run: |
        cd /c/Miniconda/
        ls -la
